# Generated by Django 3.1.2 on 2020-10-29 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interpreters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('ongoing', 'ongoing'), ('canceled', 'canceled'), ('completed', 'completed'), ('rescheduled', 'rescheduled'), ('in review', 'in review')], default='ongoing', max_length=20)),
                ('interpreter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interpreters.interpreter')),
            ],
        ),
    ]
