# Generated by Django 3.1.2 on 2020-11-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201101_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='role',
            field=models.CharField(choices=[('JBI', 'JBI'), ('USER', 'USER'), ('ADMIN', 'ADMIN')], default='USER', max_length=10),
        ),
    ]
