# Generated by Django 3.1.2 on 2020-11-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jbidetails_jbi_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jbidetails',
            name='id',
        ),
        migrations.AddField(
            model_name='jbidetails',
            name='jbi_username',
            field=models.CharField(default=None, max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
