# Generated by Django 3.1.2 on 2020-11-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201102_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jbidetails',
            name='jbi_username',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
