# Generated by Django 3.1.2 on 2020-11-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201102_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='jbidetails',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
